version: '2'
services:
  api:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HTTP_PORT=3000
    links:
      - mongodb:mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./databases:/data/db
