version: '2'
services:
  api:
    build: .
    working_dir: /usr/src/app
    command: ./entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HTTP_PORT=3000
      - ACCESS_KEY=
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./databases:/data/db
